### ISSUE TITLE
adding a pattern to crafter causes system to forget itself

### ISSUE THREAD

**Issue by kreezxil** [kreezxil/World-of-Dragons-A-New-Age#40]
I have to break and replace a refined storage block after adding a new recipe to the crafting system each time to make the system refresh itself.

client latest.log: http://sprunge.us/4ELtSh
server latest.log: http://paste.ubuntu.com/p/k4kJBPMgk4/

**Comment by kreezxil** [comment]
https://github.com/raoulvdberge/refinedstorage/issues/2346

**Comment by kreezxil** [comment]
and this one is 4 days old, we're expecting too much from the mod dev community apparently.

**Comment by kreezxil** [comment]
possibly fixed in this update

**Comment by raoulvdberge** [comment]
@kreezxil  You kind of are. I was busy the last few weeks. I didn't have the time to work on fixing bugs. I'd also like to remind you that you are playing an alpha version of the mod, one of the first for 1.14 (that took 2 months to port). So please adjust your expectations accordingly.

**Comment by kreezxil** [comment]
They've been adjusted @raoulvdberge it's why I made the statement. and thank you for the fix.

**Comment by raoulvdberge** [comment]
Why did you close this issue? I didn't fix anything yet.


This isn't fixed: https://github.com/raoulvdberge/refinedstorage/issues/2346

This IS fixed: https://github.com/raoulvdberge/refinedstorage/issues/2345

**Comment by kreezxil** [comment]
long day.
